// This file has been split into individual per-strategy files.
// See the following files in this directory:
// - ReplayDayTradingPipeline.cs
// - ReplayScannerSymbolSelectionModule.cs
// - Ovl001FlattenReversalAndGivebackCapStrategy.cs
// - ReplayScannerSingleShotEntryStrategy.cs
// - Tmg001BracketExitStrategy.cs
// - Tmg002BreakEvenEscalationStrategy.cs
// - Tmg003TrailingProgressionStrategy.cs
// - Tmg004PartialTakeProfitRunnerTrailStrategy.cs
// - Tmg005TimeStopStrategy.cs
// - Tmg006VolatilityAdaptiveExitStrategy.cs
// - Tmg007DrawdownDeriskStrategy.cs
// - Tmg008SessionVwapReversionExitStrategy.cs
// - Tmg009LiquiditySpreadExitStrategy.cs
// - Tmg010EventRiskCooldownGuardStrategy.cs
// - Tmg011StallExitGuardStrategy.cs
// - Tmg012PnlCapExitStrategy.cs
// - Tmg013SpreadPersistenceExitStrategy.cs
// - Tmg014GapRiskExitStrategy.cs
// - Tmg015AdverseDriftExitStrategy.cs
// - Tmg016PeakPullbackExitStrategy.cs
// - Tmg017MicrostructureStressExitStrategy.cs
// - Tmg018StaleFavorableMoveExitStrategy.cs
// - Tmg019RollingAdverseWindowExitStrategy.cs
// - Tmg020UnderperformanceTimeoutExitStrategy.cs
// - Tmg021QuotePressureExitStrategy.cs
// - Tmg022VolatilityShockWindowExitStrategy.cs
// - Tmg023ProfitReversionFailsafeExitStrategy.cs
// - Tmg024RangeCompressionExitStrategy.cs
// - Tmg025RollingVolatilityFloorExitStrategy.cs
// - Tmg026ChopAdverseExitStrategy.cs
// - Tmg027TrendExhaustionExitStrategy.cs
// - Tmg028ReversalAccelerationExitStrategy.cs
// - Tmg029SustainedReversionExitStrategy.cs
// - Tmg030RecoveryFailureExitStrategy.cs
// - Tmg031ReboundStallExitStrategy.cs
// - Tmg032WeakBounceFailureExitStrategy.cs
// - Tmg033ReboundRollunderExitStrategy.cs
// - Tmg034PostReboundFadeExitStrategy.cs
// - Tmg035ReboundRejectionAccelExitStrategy.cs
// - Tmg036RejectionStallBreakExitStrategy.cs
// - Tmg037RejectionReboundFailExitStrategy.cs
// - Tmg038RejectionContinuationConfirmExitStrategy.cs
// - Tmg039DoubleRejectionWeakReboundExitStrategy.cs
// - Tmg040DoubleReboundFailureExitStrategy.cs
// - Tmg041TripleStepBreakExitStrategy.cs
// - Tmg042ReboundPullbackFailExitStrategy.cs
// - Tmg043ReboundPullbackRejectionExitStrategy.cs
// - Tmg044ReboundPullbackRejectionConfirmExitStrategy.cs
// - Tmg045ReboundPullbackRejectionConfirmFailReboundExitStrategy.cs
// - Tmg046ReboundPullbackRejectionConfirmFailReboundBreakdownExitStrategy.cs
// - Tmg047ReboundPullbackRejectionConfirmFailReboundBreakdownConfirmExitStrategy.cs
// - Tmg048MtfCandleReversalExitStrategy.cs
// - Tmg049MtfRegimeAtrExitStrategy.cs
// - Eod001ForceFlatStrategy.cs